version: "3.7"
services:
  kafka-manager:
    image: localhost:8082/kafka-manager
    ports:
      - "9071:9099"
    networks:
      - trackago
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - _PRODUCER_ACTIVE=false
      - _PRODUCER_ADRESS=localhost:9093
      - _CONSUMER_ACTIVE=true
      - _CONSUMER_ADRESS=localhost:9093
      - _KAFKA_GROUP_ID=transfergroup
      - _CONSUMER_TOPIC=transfer
      - _SPRING_PROFILE=prod
networks:
  trackago:
